CREATE DATABASE Locadora_Manha;
USE Locadora_Manha;

CREATE TABLE Empresa( --ATRIBUTO SEMPRE DENTRO DO PARENTESES E ANTES DO PARENTESES É A ENTIDADE
		IDEmpresa INT PRIMARY KEY IDENTITY, -- PRIMARY KEY É A CHAVE PRIMARIA --IDENTITY NÃO DEIXA REPETIR NUMERO SEQUENCIAL 'AUTO INCREMENTO'
		Nome     VARCHAR(200) NOT NULL --NOT NULL ELE EXIGE QUE O COMPO NÃO PODE PASSAR VAZIO, E O (200) É O MAXIMO DE CARACTERES QUE PODE TER NO CAMPO -- char ocupa os espaços usados só, varchar vc declara no banco o tabmanho max
		);

CREATE TABLE Cliente(
		IDCliente INT PRIMARY KEY IDENTITY,
		Nome VARCHAR(200) NOT NULL,
		CPF INT 
		);

CREATE TABLE Marca(
		IDMarca INT PRIMARY KEY IDENTITY,
		Nome VARCHAR(200) NOT NULL
);

CREATE TABLE Modelo(
		IDModelo INT PRIMARY KEY IDENTITY,
		Nome VARCHAR (200) NOT NULL,
		IDMarca INT FOREIGN KEY REFERENCES Marca (IDMarca)
);

CREATE TABLE Veiculo (
		IDVeiculo INT PRIMARY KEY IDENTITY,
		Placa VARCHAR (8) NOT NULL,
		IDEmpresa INT FOREIGN KEY REFERENCES Empresa(IDEmpresa),
		IDModelo INT FOREIGN KEY REFERENCES Modelo(IDModelo)
);

CREATE TABLE Aluguel(
		IDAluguel INT PRIMARY KEY IDENTITY,
		DataInicio DATE,
		DataFim DATE,
		IDCliente INT FOREIGN KEY REFERENCES Cliente(IDCliente),
		IDVeiculo INT FOREIGN KEY REFERENCES Veiculo(IDVeiculo)
);


