-- comando para criar banco de dados
-- DDL Linguagem de Definição de dados
CREATE DATABASE RoteiroLivros;

USE RoteiroLivros;

	CREATE TABLE Generos( --ATRIBUTO SEMPRE DENTRO DO PARENTESES E ANTES DO PARENTESES É A ENTIDADE
		IDGenero INT PRIMARY KEY IDENTITY, -- PRIMARY KEY É A CHAVE PRIMARIA --IDENTITY NÃO DEIXA REPETIR NUMERO SEQUENCIAL 'AUTO INCREMENTO'
		Nome     VARCHAR(200) NOT NULL --NOT NULL ELE EXIGE QUE O COMPO NÃO PODE PASSAR VAZIO, E O (200) É O MAXIMO DE CARACTERES QUE PODE TER NO CAMPO -- char ocupa os espaços usados só, varchar vc declara no banco o tabmanho max
		);

	CREATE TABLE Autores (
		IDAutor INT PRIMARY KEY IDENTITY,
		Nome    VARCHAR(200) NOT NULL 
		);
	 
	CREATE TABLE Livros (
		IDLivro  INT PRIMARY KEY IDENTITY,
		Titulo   VARCHAR(255), --CHAVES ESTRANGEIRAS VEM SEMPRE POR ULTIMO 
		IDGenero INT FOREIGN KEY REFERENCES Generos (IDGenero),  --A CHAVE ESTRANGEIRA DEVE TER O MEMSO TIPO DA ORIGEM DEDE ex:INT -- Generos (IDGenero) NOME TABELA depois ATRIBUTO
		IDAutor  INT FOREIGN KEY REFERENCES Autores (IDAutor)
		);

	--DQL COMANDO DE CONSULTA

	SELECT * FROM Autores;
	SELECT * FROM Generos;
	SELECT * FROM Livros;