CREATE DATABASE OPTUS_MANHA;
USE OPTUS_MANHA;

CREATE TABLE Artista(
	 IDArtista INT PRIMARY KEY IDENTITY,
	 Nome VARCHAR (100) NOT NULL
	 );

CREATE TABLE Estilo(
	IDEstilo INT PRIMARY KEY IDENTITY,
	Nome VARCHAR (100) NOT NULL
	);

CREATE TABLE TipoUsuario (
	IDTipoUsuario INT PRIMARY KEY IDENTITY,
	Titulo VARCHAR (100) NOT NULL
	);

	SELECT * FROM TipoUsuario;